import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";
import { sanityClient, urlFor } from "../lib/sanity";

const recipesQuery = `*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage
}`;

export default function Home({ recipes }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Charles kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to Charles Kitchen</h1>

        <ul>
          {recipes?.length > 0 &&
            recipes.map((recipe) => (
              <li key={recipe._id}>
                <Link href={`/recipes/${recipe.slug.current}`}>
                  <a>
                    <Image
                      src={urlFor(recipe.mainImage).url()}
                      height={250}
                      width={250}
                      alt={recipe.name}
                    />
                    <span>{recipe.name}</span>
                  </a>
                </Link>
              </li>
            ))}
        </ul>
      </main>

      <footer></footer>
    </div>
  );
}

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipesQuery);
  return { props: { recipes } };
}
